# https://docs.projectcalico.org/getting-started/kubernetes/self-managed-onprem/onpremises
- name: Deploy CNI
  hosts: master
  gather_facts: no
  tasks:
    - name: Deploy Calico
      become: yes
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml --kubeconfig=/etc/kubernetes/admin.conf
