- name: Update Controle Plane
  hosts:
    - masters
  gather_facts: no
  become: yes
  tasks:
    - name: Check if stash file exists
      stat: 
        path:  /etc/kubernetes/manifests.stash
      register: stash
    - name: Stash original static pods
      when: stash.stat.exists == false
      copy:
        src: /etc/kubernetes/manifests/
        dest: /etc/kubernetes/manifests.stash/
        remote_src: yes
        directory_mode: yes

    - name: Copy stash to staging
      copy:
        src: /etc/kubernetes/manifests.stash/
        dest: /etc/kubernetes/manifests.staging/
        remote_src: yes
        directory_mode: yes

    - name: Create config directory
      file:
        path: /etc/kubernetes/kube-apiserver
        state: directory
        mode: u+rwx,g+rx,o+rx
    - name: Create volume
      lineinfile:
        path: /etc/kubernetes/manifests.staging/kube-apiserver.yaml
        insertafter: '\s*volumes:'
        line: |2-
            - hostPath:
                path: /etc/kubernetes/kube-apiserver
                type: DirectoryOrCreate
              name: kube-apiserver-config
    - name: Mount volume
      lineinfile:
        path: /etc/kubernetes/manifests.staging/kube-apiserver.yaml
        insertafter: '\s*volumeMounts:'
        line: |2-
              - mountPath: /etc/kubernetes/kube-apiserver
                name: kube-apiserver-config

    - name: Create audit config
      copy:
        dest: /etc/kubernetes/kube-apiserver/audit.yaml
        mode: u+rwx,g+rx,o+rx
        content: |
          apiVersion: audit.k8s.io/v1
          kind: Policy
          rules:
          - level: RequestResponse
            resources:
            - group: ""
              resources:
              - secrets
              - namespaces
              - pods
              - services
              - serviceaccounts
            namespaces: ["audited"]
    - name: Enable Audit
      lineinfile:
        path: /etc/kubernetes/manifests.staging/kube-apiserver.yaml
        insertafter: '\s*- kube-apiserver'
        line: |2-
              - --audit-policy-file=/etc/kubernetes/kube-apiserver/audit.yaml
              - --audit-log-path=-

    - name: Enable json loging for API Server
      lineinfile:
        path: /etc/kubernetes/manifests.staging/kube-apiserver.yaml
        insertafter: '\s*- kube-apiserver'
        line: '    - --logging-format=json'
    - name: Enable json loging for Controller Manager
      lineinfile:
        path: /etc/kubernetes/manifests.staging/kube-controller-manager.yaml
        insertafter: '\s*- kube-controller-manager'
        line: '    - --logging-format=json'
    - name: Enable json loging for Scheduler
      lineinfile:
        path: /etc/kubernetes/manifests.staging/kube-scheduler.yaml
        insertafter: '\s*- kube-scheduler'
        line: '    - --logging-format=json'

    - name: Replace static pods with staging
      copy:
        src: /etc/kubernetes/manifests.staging/
        dest: /etc/kubernetes/manifests/
        remote_src: yes
        directory_mode: yes
    - name: Remove staging
      file:
        path: /etc/kubernetes/manifests.staging
        state: absent

- name: Update kubelet configs
  hosts:
    - masters
    - workers
  gather_facts: no
  become: yes
  tasks:
    - name: Enable json loging for Kubelet
      replace:
        path: /var/lib/kubelet/kubeadm-flags.env
        regexp: '^KUBELET_KUBEADM_ARGS="(.*)$'
        replace: 'KUBELET_KUBEADM_ARGS="--logging-format=json \1'
        backup: yes
    - name: Restart kubelet service
      service:
        name: kubelet
        state: restarted