
- name: Installs Container Runtime
  import_playbook: cri-containerd.yaml
  # import_playbook: cri-docker.yaml
  # import_playbook: cri-crio.yaml

- name: Install Kubernetes binaries
  hosts:
    - masters
    - workers
  gather_facts: no
  become: yes
  tasks:
    - name: Add Kubernetes GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - name: Add Kubernetes repo
      apt_repository:
        repo: 'deb https://apt.kubernetes.io/ kubernetes-xenial main'
    - name: Install Kubernetes packages
      apt:
        name:
          - kubelet={{kube_version}}-00
          - kubeadm={{kube_version}}-00
          - kubectl={{kube_version}}-00
        update_cache: yes

- name: Init master
  hosts: master
  become: yes
  tasks:
    - name: Creates config.yaml for kubeadm
      template:
        src: kubeadm-config.yaml.j2
        dest: config.yaml
    - name: Copy policy.yaml
      copy:
        src: kubernetes
        dest: /etc
    - name: Run Kubeadm
      shell: kubeadm init --config config.yaml
      register: kubeadm_init
      args:
        creates: /etc/kubernetes/admin.conf
    - name: kubeadm init output
      debug:
        var: kubeadm_init.stderr_lines
    - name: Get Kubernets join cluster command
      shell: kubeadm token create --print-join-command
      register: join_cmd
    - name: Export join command
      set_fact:
        join_cmd: "{{ join_cmd.stdout }}"

- name: Deploy Container Network
  import_playbook: cni-calico.yaml
  # import_playbook: cni-flannel.yaml

- name: Join master
  hosts: workers
  gather_facts: no
  become: yes
  tasks:
    - name: Joining cluster
      shell: "{{ hostvars['master'].join_cmd }}"

- name: Updates local kubectl config
  hosts: master
  gather_facts: no
  tasks:
    - name: Copy admin.conf to localhost
      become: yes
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{lookup('env','HOME')}}/.kube/kubeadm.config"
        flat: yes
