apiVersion: v1
kind: Pod
metadata:
  name: instrumented-logs
  labels:
      admission.datadoghq.com/enabled: "true"
      tags.datadoghq.com/env: learn-by-example
      tags.datadoghq.com/service: instrumented-logs
      tags.datadoghq.com/version: "0.1"
spec:
  containers:
  - name: instrumented-logs
    image: yaalexf/instrumented-logs
    imagePullPolicy: Always
    resources:
      requests:
        memory: "160Mi"
        cpu: "10m"
      limits:
        memory: "256Mi"
        cpu: "200m"
