apiVersion: v1
kind: Pod
metadata:
  name: instrumented-logs
spec:
  containers:
  - name: instrumented-logs
    image: yaalexf/instrumented-logs
    imagePullPolicy: Always
    resources:
      requests:
        memory: "256Mi"
        cpu: "20m"
      limits:
        memory: "512Mi"
        cpu: "200m"
    env:
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP

