apiVersion: v1
kind: Namespace
metadata:
  name: tags-tags-tags
  labels:
    tags.lbe.datadog.com/tag: namespace-label
---
apiVersion: v1
kind: Pod
metadata:
  name: tags-tags-tags
  namespace: tags-tags-tags
  labels:
    tags.lbe.datadog.com/tag: pod-label
  annotations:
    tags.lbe.datadog.com/tag: pod-annotation
    ad.datadoghq.com/tags: |-
      {"tag-origin": "ad-annotations"}
spec:
  containers:
  - name: tags-tags-tags
    image: yaalexf/tags
    imagePullPolicy: Always
    resources:
      requests:
        memory: "128Mi"
        cpu: "20m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    env:
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: DD_TAGS
      value: tag-origin:app-env-var

